name: sliver_appbar_demo
description: A Flutter project demonstrating SliverAppBar.

# Prevent accidental publishing
publish_to: 'none'

# Version of your app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# --------------------------------------------------
# THIS IS THE MAIN FLUTTER SECTION
# --------------------------------------------------

flutter:

  # Enables Material Icons
  uses-material-design: true

  # Adding assets folder
  assets:
    -  assets/screenshot/rwanda.png




